<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeFile="Home.aspx.cs" Inherits="Home" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
    
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <asp:LoginView ID="CarsView" runat="server">
        <AnonymousTemplate>
            <asp:GridView id="GridView1" runat="Server" 
                AllowSorting="True" 
                DataKeyNames="Id"
                AutoGenerateColumns="False"
                AutoGenerateDeleteButton="False"
                AutoGenerateEditButton="false"
                AllowPaging="true"
                DataSourceID="SqlDateSource">
                <Columns>
                    <asp:BoundField DataField="Id" HeaderText="Id" SortExpression="Id" />
                    <asp:BoundField DataField="Model" HeaderText="Model" SortExpression="Model" />
                    <asp:BoundField DataField="MaxSpeed" HeaderText="Max Speed" SortExpression="MaxSpeed" />
                    <asp:BoundField DataField="Power" HeaderText="Power" SortExpression="Power" />
                    <asp:BoundField DataField="Color" HeaderText="Color" SortExpression="Color" />
                    <asp:BoundField DataField="Fabrication_Date" HeaderText="Fabrication Date" SortExpression="Fabrication_Date" />
                </Columns>>
            </asp:GridView>
        </AnonymousTemplate>  

    </asp:LoginView>
    <asp:SqlDataSource ID="SqlDataSource" runat="server" ConnectionString="<#$ ConnectionString:DefaultConnection %>"
        SelectCommand="SELECT * FROM [Cars]"></asp:SqlDataSource>
</asp:Content>

